import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import Nav from "@/components/Nav";
import doctorsDummyData from "/data/doctorsDummyData.json";
import specialistsDummy from "/data/specialistsDummyData.json";
import { useRouter } from "next/router";
import { storageClient } from "@/appWrite-client/settings.config";

const specialistsArray = specialistsDummy.specialists;

export default function Category({ specialist }) {
  const [images, setImages] = useState(null);
  const doctorsArray = doctorsDummyData.doctors;
  const router = useRouter();

  const bucketID = process.env.BUCKET_ID || process.env.NEXT_PUBLIC_BUCKET_ID;

  useEffect(() => {
    const storage = storageClient.listFiles(bucketID);
    storage.then(
      function (response) {
        setImages(response.files);
      },
      function (error) {
        console.log(error);
      }
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>{specialist.type} | NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center w-screen">
        <div className="flex flex-col w-[95%] max-w-[900px] h-screen pt-5 pb-14 xl:pt-24 overflow-hidden">
          <Nav />

          <div>
            <button
              className="px-1 text-black dark:text-white"
              onClick={() => router.back()}
            >
              &larr; back
            </button>
          </div>

          <h1 className="text-4xl text-center md:text-6xl text-[#2A9988]">
            {specialist.type + "s"}
          </h1>

          <div className="h-full mt-5 overflow-hidden md:mt-10">
            <div
              className={`w-full h-full overflow-scroll grid grid-cols-1 md:grid-cols-2 gap-10 pb-12`}
            >
              {images &&
                doctorsArray.map((data, index) => {
                  const imageURL = storageClient.getFilePreview(
                    bucketID,
                    images[index].$id
                  );

                  return (
                    <div
                      className="flex flex-col w-full h-fit bg-[#FCFCFC] rounded-lg shadow-lg"
                      key={data.id}
                    >
                      <div className="flex items-center justify-between w-full p-4">
                        <div className="flex items-center gap-2">
                          <div className="relative w-28 aspect-square">
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                              src={imageURL}
                              alt="ProfilePic"
                              className="rounded-full"
                            />
                          </div>
                          <div>
                            <h1 className="text-2xl text-black">{data.name}</h1>
                            <p className="text-lg text-black">{data.degrees}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticPaths() {
  const paths = specialistsArray.map((specialist) => ({
    params: { category: specialist.id.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const { category } = params;

  const specialist = specialistsArray.find(
    (spec) => spec.id.toString() === category
  );

  return {
    props: {
      specialist,
    },
  };
}
