import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Splash from "@/components/Splash-Screen/Splash";
import landingPageImg from "../public/landingPage.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Splash />
        <section className="flex flex-col items-center justify-start w-full min-h-screen gap-12 pt-12 xl:gap-10 lg:pt-8">
          <div className="flex flex-col items-center w-full px-20 sm:px-4">
            <Image
              src={landingPageImg}
              width={400}
              height={400}
              alt="placeholderImg"
            />
          </div>
          <div className="flex flex-col items-center w-full px-4 text-black dark:text-white sm:px-20">
            <h1 className="w-full text-4xl text-center">
              Get Medical Consultation from Home
            </h1>
            <br />
            <p className="w-full max-w-lg text-lg text-center">
              Welcome to <b className="text-[#2A9988]">NextGen Doctors</b> where
              you can receive medical care from the comfort of your own home.
            </p>
            <div className="flex items-center justify-center w-full gap-4 mt-6 sm:mt-10">
              <Link
                href="/sign-up"
                className="p-2 w-1/2 bg-[#2a9988] hover:bg-[#1C665B] duration-500 rounded-md text-white text-xl max-w-[250px] text-center"
              >
                Get Started
              </Link>
              <Link
                href="/login"
                className="p-2 w-1/2 border border-[#2a9988] bg-[#2a9988] hover:bg-[#1C665B] dark:bg-transparent dark:hover:bg-[#1C665B] duration-500 rounded-md text-white text-xl max-w-[250px] text-center"
              >
                Login
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-end w-full text-black dark:text-white">
            <div className="flex flex-col items-center w-full px-4 sm:px-20">
              <h1 className="w-full text-3xl text-center">
                Expert Care from Trusted Medical Professionals
              </h1>
              <br />
              <p className="w-full max-w-lg text-base text-center xl:text-lg sm:font-normal">
                Our medical professionals undergo a rigorous screening and
                selection process before they join our team. When you receive an
                online medical consultation through our service, you can trust
                that you&apos;re getting expert advice and guidance from a
                qualified medical professional.
              </p>
            </div>
          </div>
          <div className="w-full flex flex-col items-end pb-20 sm:pb-24 bg-[#2A9988] text-white py-10 overflow-hidden relative grow">
            <Image
              src={"/stetoscope.svg"}
              width={600}
              height={600}
              alt="placeholderImg"
              className="absolute overflow-hidden blur-sm"
            />
            <h1 className="w-full px-5 text-2xl font-bold text-left sm:px-20">
              FAQs:
            </h1>
            <br />
            <ul className="z-10 grid grid-cols-1 gap-10 px-5 md:grid-cols-2 xl:grid-cols-3 sm:px-20 ">
              <div>
                <li className="text-xl">
                  How do I sign up for an online medical consultation?
                </li>
                <li className="text-sm font-light">
                  Signing up is easy! Simply create an account on our website
                  and provide some basic information about yourself. Once
                  you&apos;ve created an account, you can schedule a
                  consultation with one of our medical professionals at a time
                  that&apos;s convenient for you.
                </li>
              </div>

              <div>
                <li className="text-xl">
                  How do I pay for my online medical consultation?
                </li>
                <li className="text-sm font-light">
                  We accept a variety of payment methods, including debit cards,
                  and Bank Transfers. You&apos;ll be asked to provide payment
                  information when you schedule your consultation.
                </li>
              </div>

              <div>
                <li className="text-xl">
                  Is my personal and medical information secure?
                </li>
                <li className="text-sm font-light">
                  Yes! We take the security and privacy of your personal and
                  medical information very seriously.
                </li>
              </div>

              <div>
                <li className="text-xl">
                  What if I need to cancel or reschedule my consultation?
                </li>
                <li className="text-sm font-light">
                  If you need to cancel or reschedule your consultation, simply
                  log in to your account and make the changes. Please note that
                  we have a 24-hour cancellation policy, so be sure to cancel or
                  reschedule at least 24 hours before your scheduled
                  consultation.
                </li>
              </div>
            </ul>
          </div>
        </section>
      </main>
    </>
  );
}
